# ===== User Configuration =====
# Note: this file is auto-generated by setup_and_run.sh, but can also be edited manually

# Reference genome path
REF="./Arabidopsis_thaliana.TAIR10.dna.toplevel.fa"

# Known-variants VCF for BQSR (optional, leave empty to skip)
KNOWN_VCF=""

# Input FASTQ files
SHORT_R1=""
SHORT_R2=""
LONG_R1=""
LONG_R2=""

# Fine-mapping interval
FINE_CHR="1"
FINE_START=10000000
FINE_END=15000000

# Number of CPU threads
THREADS=8

# Output directory
OUTDIR="./bsa_output"
