# ===== User Configuration =====
# Note: this file is auto-generated by setup_and_run.sh, but can also be edited manually

# Reference genome path
REF="./reference/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa"

# Known-variants VCF for BQSR (optional, leave empty to skip)
KNOWN_VCF=""

# Input FASTQ files
MUT_R1="RawData/mut_pool/F2-611-mut_1.fq.gz"
MUT_R2="RawData/mut_pool/F2-611-mut_2.fq.gz"
WT_R1="RawData/wt_pool/F2-611-wt_1.fq.gz"
WT_R2="RawData/wt_pool/F2-611-wt_2.fq.gz"

# Fine-mapping interval
FINE_CHR="1"
FINE_START=10000000
FINE_END=15000000

# Number of CPU threads
THREADS=8

# Output directory
OUTDIR="./bsa_output"
